[build]
target = "x86_64-unknown-linux-gnu"

[target.powerpc-unknown-linux-gnu]
linker = "powerpc-linux-gnu-gcc"
runner = "qemu-ppc -L /usr/powerpc-linux-gnu"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
